In [174]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

In [175]:
import pandas as pd

# -------------------------------
# Load the data
# -------------------------------
input_file = "results_deterministic_approximate.csv"
df = pd.read_csv(input_file, header=None, names=["file", "objective", "time", "solutions"])

# -------------------------------
# Robust filename parser
# -------------------------------
def split_filename(fname):
    fname = fname.replace(".json", "")
    parts = fname.split("_")
    
    # Handle short/malformed names
    if len(parts) < 4:
        return pd.Series([fname, "", "", ""])  # fallback: just filename

    # Multi-part instance names (e.g., transoptas_5pso, deepela_large_r1)
    if len(parts) > 4:
        instance_name = "_".join(parts[:-3])
        measure = parts[-3]
        percentile = parts[-2]
        algorithm = parts[-1]
    else:
        instance_name = parts[0]
        measure = parts[1]
        percentile = parts[2]
        algorithm = parts[3]

    return pd.Series([instance_name, measure, percentile, algorithm])

# Apply parser
df[["instance_name", "measure", "percentile", "algorithm"]] = df["file"].apply(split_filename)

# Reorder columns
df = df[["instance_name", "measure", "percentile", "algorithm", "objective", "time", "solutions"]]

# Preview
df.head(20)

,instance_name,measure,percentile,algorithm,objective,time,solutions
0,ela,cosine,p95,alg0,7805,23.606821,7805
1,transoptas_5pso,correlation,p80,alg1,5,1.834159,5
2,tinytla,seuclidean,p95,alg0,7463,17.956013,7463
3,transoptas_5pso,correlation,p20,alg0,963,131.665430,963
4,deepela_large_r1,cosine,p80,alg1,64,14.691024,64
5,transoptas_5pso,correlation,p20,alg1,1,3.277177,1
6,transoptas_5pso,seuclidean,p50,alg0,2318,78.848311,2318
7,doe2vec,seuclidean,p90,alg1,6,1.373848,6
8,doe2vec,correlation,p20,alg1,3,4.489700,3
9,doe2vec,correlation,p95,alg1,4544,300.377671,4544
10,deepela_large_r1,seuclidean,p80,alg0,5212,43.035083,5212
11,ela,seuclidean,p20,alg1,0,0.000249,0
12,tinytla,correlation,p50,alg0,3449,77.117804,3449
13,transoptas_5pso,seuclidean,p95,alg0,6785,16.835849,6785
14,deepela_large_r1,correlation,p95,alg1,712,84.562076,712
15,ela,cosine,p20,alg1,1,6.215203,1
16,ela,correlation,p90,alg1,93,9.009333,93
17,ela,seuclidean,p10,alg1,0,0.000221,0
18,ela,seuclidean,p90,alg0,0,0.000019,0
19,tinytla,seuclidean,p50,alg0,2585,92.419273,2585

In [176]:
#results_exact:

import pandas as pd

# -------------------------------
# Step 1: Load the CSV
# -------------------------------
# -------------------------------
# Step 1: Load CSV and inspect columns
# -------------------------------
input_file = "results_exact.csv"

# Try reading with headers
df_exact = pd.read_csv(input_file)

print("Columns in CSV:", df_exact.columns.tolist())
df_exact.columns = df_exact.columns.str.strip()

# -------------------------------
# Step 2: Robust filename parser
# -------------------------------
def split_filename(fname):
    fname = fname.replace(".json", "")
    parts = fname.split("_")
    
    # Handle short/malformed names
    if len(parts) < 4:
        return pd.Series([fname, "", "", ""])  # fallback

    # Multi-part instance names (e.g., transoptas_5pso, deepela_large_r1)
    if len(parts) > 4:
        instance_name = "_".join(parts[:-3])
        measure = parts[-3]
        percentile = parts[-2]
        algorithm = parts[-1]
    else:
        instance_name = parts[0]
        measure = parts[1]
        percentile = parts[2]
        algorithm = parts[3]

    return pd.Series([instance_name, measure, percentile, algorithm])

# Apply parser
df_exact[["instance_name", "measure", "percentile", "algorithm"]] = df_exact["fname"].apply(split_filename)

# -------------------------------
# Step 3: Reorder columns
# -------------------------------
df_exact = df_exact[["instance_name", "measure", "percentile", "algorithm", "nodes", "edges", "objective", "lb"]]

# -------------------------------
# Step 4: Preview
# -------------------------------
df_exact.head(2)

Columns in CSV: ['fname', ' nodes', ' edges', ' objective', ' lb']

,instance_name,measure,percentile,algorithm,nodes,edges,objective,lb
0,deepela_large_r1,correlation,p80,alg1,8280,6971814,2.0,2
1,deepela_large_r1,correlation,p90,alg1,8280,3680040,6.0,6

In [177]:
#results_kmis_online_mis.csv


import pandas as pd
import ast

# Load CSV
nclue_file = "results_kmis_online_mis.csv"

df_nclue = pd.read_csv(nclue_file)
df_nclue.columns = df_nclue.columns.str.strip()


def split_nclue_filename(fname):
    fname = fname.replace(".out", "")
    parts = fname.split("_")
    
    # The last three parts are measure, percentile, seed
    seed = parts[-1]
    percentile = parts[-2]
    measure = parts[-3]
    
    # Everything before that is instance name
    instance_name = "_".join(parts[:-3])
    
    return pd.Series([instance_name, measure, percentile, seed])

# Apply parser
df_nclue[["instance_name", "measure", "percentile", "seed"]] = df_nclue["file"].apply(split_nclue_filename)

# Convert solution string to list if needed
df_nclue["solution"] = df_nclue["solution"].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

# Reorder columns
df_nclue = df_nclue[["instance_name", "measure", "percentile", "seed", "solution", "objective"]]

# Preview
df_nclue.head(20)

       instance_name      measure percentile seed    solution  objective
0   deepela_large_r1  correlation        p10   20  [Ellipsis]        505
1   deepela_large_r1  correlation        p10   30  [Ellipsis]        505
2   deepela_large_r1  correlation        p10   50  [Ellipsis]        504
3   deepela_large_r1  correlation        p20   10  [Ellipsis]       1055
4   deepela_large_r1  correlation        p20   20  [Ellipsis]       1055
5   deepela_large_r1  correlation        p20   40  [Ellipsis]       1055
6   deepela_large_r1  correlation        p50   10  [Ellipsis]       2553
7   deepela_large_r1  correlation        p50   20  [Ellipsis]       2551
8   deepela_large_r1  correlation        p50   30  [Ellipsis]       2553
9   deepela_large_r1  correlation        p50   40  [Ellipsis]       2551
10  deepela_large_r1  correlation        p50   50  [Ellipsis]       2553
11  deepela_large_r1  correlation        p80   10  [Ellipsis]       4249
12  deepela_large_r1  correlation        p80   20  [Ellipsis]       4235
13  deepela_large_r1  correlation        p80   30  [Ellipsis]       4248
14  deepela_large_r1  correlation        p80   40  [Ellipsis]       4249
15  deepela_large_r1  correlation        p80   50  [Ellipsis]       4249
16  deepela_large_r1  correlation        p90   10  [Ellipsis]       5103
17  deepela_large_r1  correlation        p90   20  [Ellipsis]       5103
18  deepela_large_r1  correlation        p90   30  [Ellipsis]       5103
19  deepela_large_r1  correlation        p90   40  [Ellipsis]       5103

In [178]:
# results_numds.csv:

import pandas as pd

# Load your CSV or TSV
df_numds = pd.read_csv("results_numds.csv", sep=" ")  # use sep="," if CSV

# Function to split filename
def split_simple_filename(fname):
    parts = fname.split("_")
    # last part is percentile
    percentile = parts[-1]
    measure = parts[-2]
    instance_name = "_".join(parts[:-2])
    return pd.Series([instance_name, measure, percentile])

# Apply parser
df_numds[["instance_name", "measure", "percentile"]] = df_numds["file"].apply(split_simple_filename)

# Reorder columns
df_numds = df_numds[["instance_name", "measure", "percentile", "seed", "objective"]]
#df_numds.rename(columns={"objective": "NUMDS"}, inplace=True)
#df_numds.drop(columns=["seed"], axis=1, inplace=True)

df_numds.head(20)

       instance_name      measure percentile  seed  objective
0                ela  correlation        p80    40          2
1    transoptas_5pso       cosine        p95    10         11
2            doe2vec       cosine        p50    30          2
3   deepela_large_r1       cosine        p10    10          1
4            doe2vec  correlation        p50    40          2
5            tinytla   seuclidean        p20    30          1
6   deepela_large_r1   seuclidean        p95    50          1
7            tinytla   seuclidean        p95    20          1
8                ela       cosine        p90    10          5
9    transoptas_5pso   seuclidean        p10    50          1
10  deepela_large_r1  correlation        p90    10          6
11  deepela_large_r1  correlation        p80    50          2
12  deepela_large_r1  correlation        p95    20         61
13   transoptas_5pso   seuclidean        p10    30          1
14               ela       cosine        p20    10          1
15           doe2vec       cosine        p90    40         41
16  deepela_large_r1  correlation        p80    30          2
17           tinytla   seuclidean        p20    10          1
18               ela       cosine        p80    30          2
19           doe2vec       cosine        p10    50          2

In [179]:
# results_redumis.csv:

import pandas as pd
import ast

# Load your CSV/TSV
df_redumis = pd.read_csv("results_redumis.csv")  # or sep="," / sep="\t" depending on file
df_redumis.columns = df_redumis.columns.str.strip()


# -------------------------------
# Step 1: Correct parser
# -------------------------------
def split_redumis_filename(fname):
    fname = fname.replace(".out", "")
    parts = fname.split("_")
    
    # Identify known measures
    measure_candidates = ["correlation", "cosine", "seuclidean"]
    measure = next((m for m in parts if m in measure_candidates), "")
    
    # Instance name: everything before measure
    measure_idx = parts.index(measure) if measure else 0
    instance_name = "_".join(parts[:measure_idx])
    
    # Percentile: first part that starts with 'p'
    percentile = next((p for p in parts if p.startswith("p")), "")
    
    # Seed: if "seed" is present
    seed = ""
    if "seed" in parts:
        seed_idx = parts.index("seed")
        seed = parts[seed_idx + 1]
    
    return pd.Series([instance_name, measure, percentile, seed])

# -------------------------------
# Step 2: Apply parser
# -------------------------------
df_redumis[["instance_name", "measure", "percentile", "seed"]] = df_redumis["file"].apply(split_redumis_filename)

# -------------------------------
# Step 3: Convert solution string to Python list
# -------------------------------
df_redumis["solution"] = df_redumis["solution"].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith("[") else []
)

# -------------------------------
# Step 4: Reorder columns
# -------------------------------
df_redumis = df_redumis[["instance_name", "measure", "percentile", "seed", "solution", "objective"]]

# -------------------------------
# Step 5: Preview
# -------------------------------
df_redumis.head(20)

       instance_name      measure percentile seed solution  objective
0   deepela_large_r1  correlation        p10            []        505
1   deepela_large_r1  correlation        p10            []        505
2   deepela_large_r1  correlation        p10            []        505
3   deepela_large_r1  correlation        p20            []       1055
4   deepela_large_r1  correlation        p20            []       1055
5   deepela_large_r1  correlation        p50            []       2553
6   deepela_large_r1  correlation        p50            []       2553
7   deepela_large_r1  correlation        p50            []       2553
8   deepela_large_r1  correlation        p80            []          0
9   deepela_large_r1  correlation        p80            []          0
10  deepela_large_r1  correlation        p80            []          0
11  deepela_large_r1  correlation        p80            []       4249
12  deepela_large_r1  correlation        p80            []       4249
13  deepela_large_r1  correlation        p80            []       4249
14  deepela_large_r1  correlation        p80            []       4249
15  deepela_large_r1  correlation        p90            []          0
16  deepela_large_r1  correlation        p90            []          0
17  deepela_large_r1  correlation        p90            []          0
18  deepela_large_r1  correlation        p90            []          0
19  deepela_large_r1  correlation        p90            []          0

In [180]:
#merge all:

df_approx = df[["instance_name", "measure", "percentile", "algorithm", "objective" ]]
df_approx_mis = df_approx[df_approx["algorithm"] == "alg0"]
df_approx_mds = df_approx[df_approx["algorithm"] == "alg1"]
#renaming
df_approx_mis.rename(columns={"objective" : "Greedy"}, inplace=True)
df_approx_mds.rename(columns={"objective" : "Greedy"}, inplace=True)

#### EXACT SOLVERS
df_exact = df_exact[["instance_name", "measure", "percentile", "algorithm", "objective", "lb"]]
df_exact_mis = df_exact[df_exact["algorithm"] == "alg0"]
df_exact_mds = df_exact[df_exact["algorithm"] == "alg1"]

df_exact_mis.rename(columns={"objective" : "CPLEX"}, inplace=True) 
df_exact_mds.rename(columns={"objective" : "CPLEX"}, inplace=True) 

df_approx_mis.drop(columns=["algorithm"], axis=1, inplace=True)
df_exact_mis.drop(columns=["algorithm"], axis=1, inplace=True)

df_approx_mds.drop(columns=["algorithm"], axis=1, inplace=True)
df_exact_mds.drop(columns=["algorithm"], axis=1, inplace=True)

### KMIS online:

df_nclue = df_nclue[["instance_name", "measure", "percentile", "seed",  "objective" ]]
df_nclue

# Group by instance_name, measure, percentile, and compute mean objective
df_nclue_grouped = df_nclue.groupby(["instance_name", "measure", "percentile"], as_index=False).agg({
    "objective": "mean"
})

df_nclue_grouped.rename(columns={"objective" : "MIS_ONLINE"}, inplace=True)
# Preview
df_nclue_grouped.head(15)

/tmp/ipykernel_201874/37198415.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_approx_mis.rename(columns={"objective" : "Greedy"}, inplace=True)
/tmp/ipykernel_201874/37198415.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_approx_mds.rename(columns={"objective" : "Greedy"}, inplace=True)
/tmp/ipykernel_201874/37198415.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_exact_mis.rename(columns={"objective" : "CPLEX"}, inplace=True)
/tmp/ipykernel_201874/37198415.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_exact_mds.rename(columns={"objective" : "CPLEX"}, inplace=True)
/tmp/ipykernel_201874/37198415.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_approx_mis.drop(columns=["algorithm"], axis=1, inplace=True)
/tmp/ipykernel_201874/37198415.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_exact_mis.drop(columns=["algorithm"], axis=1, inplace=True)
/tmp/ipykernel_201874/37198415.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_approx_mds.drop(columns=["algorithm"], axis=1, inplace=True)
/tmp/ipykernel_201874/37198415.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_exact_mds.drop(columns=["algorithm"], axis=1, inplace=True)

       instance_name      measure percentile   MIS_ONLINE
0   deepela_large_r1  correlation        p10   504.666667
1   deepela_large_r1  correlation        p20  1055.000000
2   deepela_large_r1  correlation        p50  2552.200000
3   deepela_large_r1  correlation        p80  4246.000000
4   deepela_large_r1  correlation        p90  5103.000000
5   deepela_large_r1  correlation        p95  5862.000000
6   deepela_large_r1       cosine        p10   507.500000
7   deepela_large_r1       cosine        p20  1049.000000
8   deepela_large_r1       cosine        p50  2550.600000
9   deepela_large_r1       cosine        p80  4250.000000
10  deepela_large_r1       cosine        p90  5123.000000
11  deepela_large_r1       cosine        p95  5841.000000
12  deepela_large_r1   seuclidean        p10   568.000000
13  deepela_large_r1   seuclidean        p20  1303.000000
14  deepela_large_r1   seuclidean        p50  3165.000000

In [181]:
## results_redumis.csv:
df_redumis = df_redumis[["instance_name", "measure", "percentile", "seed",  "objective" ]]
df_redumis

# Group by instance_name, measure, percentile, and compute mean objective
df_redumis_grouped = df_redumis.groupby(["instance_name", "measure", "percentile"], as_index=False).agg({
    "objective": "mean"
})

df_redumis_grouped.rename(columns={"objective" : "REDUMIS"}, inplace=True)
#df_redumis_grouped.drop(columns=["seed"], axis=1, inplace=True)
# Preview
df_redumis_grouped.head(15)

       instance_name      measure percentile  REDUMIS
0   deepela_large_r1  correlation        p10    505.0
1   deepela_large_r1  correlation        p20   1055.0
2   deepela_large_r1  correlation        p50   2553.0
3   deepela_large_r1  correlation        p80   2428.0
4   deepela_large_r1  correlation        p90   2268.0
5   deepela_large_r1  correlation        p95   5862.0
6   deepela_large_r1       cosine        p10    508.0
7   deepela_large_r1       cosine        p20   1049.0
8   deepela_large_r1       cosine        p50   2040.8
9   deepela_large_r1       cosine        p80   3400.0
10  deepela_large_r1       cosine        p90   5123.0
11  deepela_large_r1       cosine        p95   5841.0
12  deepela_large_r1   seuclidean        p10    568.0
13  deepela_large_r1   seuclidean        p20   1303.0
14  deepela_large_r1   seuclidean        p50   3165.0

In [182]:
## numds
df_numds
df_numds = df_numds[["instance_name", "measure", "percentile", "seed",  "objective" ]]

# Group by instance_name, measure, percentile, and compute mean objective
df_numds_grouped = df_numds.groupby(["instance_name", "measure", "percentile"], as_index=False).agg({
                "objective": "mean"
})
df_numds_grouped.rename(columns={"objective" : "NUMDS" },   inplace=True)

# Preview
df_numds_grouped.head(15)

       instance_name      measure percentile  NUMDS
0   deepela_large_r1  correlation        p10    1.0
1   deepela_large_r1  correlation        p20    1.0
2   deepela_large_r1  correlation        p50    2.0
3   deepela_large_r1  correlation        p80    2.0
4   deepela_large_r1  correlation        p90    6.0
5   deepela_large_r1  correlation        p95   61.0
6   deepela_large_r1       cosine        p10    1.0
7   deepela_large_r1       cosine        p20    1.0
8   deepela_large_r1       cosine        p50    2.0
9   deepela_large_r1       cosine        p80    2.0
10  deepela_large_r1       cosine        p90    5.0
11  deepela_large_r1       cosine        p95   51.0
12  deepela_large_r1   seuclidean        p10    1.0
13  deepela_large_r1   seuclidean        p20    1.0
14  deepela_large_r1   seuclidean        p50    1.0

In [183]:
## TO MERGE (MIS solvers):  

print("MIS solvers")
# List of dataframes to merge
dfs_to_merge = [df_approx_mis, df_exact_mis, df_nclue_grouped, df_redumis_grouped]

# Start with the first dataframe
df_merged = dfs_to_merge[0]

# Merge sequentially on the key columns
for df in dfs_to_merge[1:]:
    df_merged = df_merged.merge(df, on=["instance_name", "measure", "percentile"], how="left")

# Preview the merged dataframe
df_merged.head(30)

df_merged.to_csv("MIS_4solvers_results.csv")

MIS solvers

In [187]:
## MDS results to merge: df_approx_mds, df_exact_mds, df_numds...

print("MDS solvers...")
# List of dataframes to merge
dfs_to_merge_mds = [ df_approx_mds, df_exact_mds, df_numds_grouped]

# Start with the first dataframe
df_merged_mds = dfs_to_merge_mds[0]

# Merge sequentially on the key columns
for df in dfs_to_merge_mds[1:]:
    df_merged_mds = df_merged_mds.merge(df, on=["instance_name", "measure", "percentile"], how="left")

# Preview the merged dataframe
df_merged_mds.to_csv("MDS_3solvers_results.csv")

df_approx_mds

MDS solvers...

        instance_name      measure percentile  Greedy
1     transoptas_5pso  correlation        p80       5
4    deepela_large_r1       cosine        p80      64
5     transoptas_5pso  correlation        p20       1
7             doe2vec   seuclidean        p90       6
8             doe2vec  correlation        p20       3
..                ...          ...        ...     ...
155   transoptas_5pso   seuclidean        p50       2
157  deepela_large_r1   seuclidean        p10       1
158           tinytla  correlation        p10       1
161               ela       cosine        p80      13
163  deepela_large_r1       cosine        p50       2

[90 rows x 4 columns]